### ISSUE TITLE
Images are not shown

### ISSUE THREAD

**Issue by GANs-and-roses** [DM-09/Anywhere-Bing-AI#1]
Thanks for the great addon, mate!

I use the addon on Archlinux Firefox developer edition 114.

When I ask for images, I can see bing is writing images in Markdown but they are not shown. There is a visual glitch meanwhile

**Comment by DM-09** [comment]
Can you show me a screen shot or video? It is hard that I check this problem.

**Comment by GANs-and-roses** [comment]
Here it shows from beginning to the end
https://www.dailymotion.com/video/x8kz7gz

**Comment by DM-09** [comment]
Can you change conversation style to Creative? and then enter the same question?

It work?

**Comment by GANs-and-roses** [comment]
Here you go: https://www.dailymotion.com/video/x8l02c6
It doesn't work

**Comment by DM-09** [comment]
I have same bug. Even basic bing ai have the bug. I think it is just Bing's bug. If you want bing to draw picture, please enter the another question at creative style chat such as 'draw sky picture'
